
function A = plotGraficoShewhart_tasa(data, media, sigma)
% plotGraficoShewhart_tasa: Gráfico de control tipo Shewhart para tasas
% Inputs:
%   - data: vector de tasas o métricas (por ejemplo, porcentaje diario)
%   - media: valor medio esperado
%   - sigma: desviación estándar

    dias = length(data); % número real de datos

    figure
    plot(1:dias, data, 'ko', 'MarkerSize', 3, 'LineStyle', 'none')
    hold on

    % Línea central
    yline(media, 'b-', 'LineWidth', 2, 'Label', '$\bar{y}$', ...
          'Interpreter', 'latex', 'LabelHorizontalAlignment', 'left');

    % Límites ±1σ, ±2σ, ±3σ
    for k = 1:2
        yline(media + k*sigma, 'r--', 'LineWidth', 1.5, ...
              'Label', sprintf('+%d$\\sigma$', k), ...
              'LabelHorizontalAlignment', 'left', 'Interpreter', 'latex');
        yline(media - k*sigma, 'r--', 'LineWidth', 1.5, ...
              'Label', sprintf('-%d$\\sigma$', k), ...
              'LabelHorizontalAlignment', 'left', 'Interpreter', 'latex');
    end
    for k = 3
        yline(media + k*sigma, 'r-', 'LineWidth', 2.5, ...
              'Label', sprintf('+%d$\\sigma$', k), ...
              'LabelHorizontalAlignment', 'left', 'Interpreter', 'latex');
        yline(media - k*sigma, 'r-', 'LineWidth', 2.5, ...
              'Label', sprintf('-%d$\\sigma$', k), ...
              'LabelHorizontalAlignment', 'left', 'Interpreter', 'latex');
    end

    title('Gráfico de Control de Shewhart (Tasa)')
    xlabel('Día')
    ylabel('%')
    grid on
    xlim([1 dias])  % ← Eje X ajustado al tamaño real de data

    % Obtener límites del eje
    xLimits = xlim;
    yLimits = ylim;

    % Esquina inferior derecha
    texto1 = {'$\bar{y}$ = ' + string(sprintf('%.2f', media)), ...
              '$\sigma$ = ' + string(sprintf('%.2f', sigma))};
    xPos1 = xLimits(2) - 0.02*(xLimits(2) - xLimits(1));
    yPos1 = yLimits(1) + 0.02*(yLimits(2) - yLimits(1));
    text(xPos1, yPos1, texto1, ...
         'HorizontalAlignment', 'right', ...
         'VerticalAlignment', 'bottom', ...
         'FontSize', 10, ...
         'Interpreter', 'latex', ...
         'BackgroundColor', 'w');

    % Esquina superior izquierda con intervalos
    texto2 = { ...
        sprintf('$\\pm1\\sigma$ (%.2f, %.2f)', media - sigma, media + sigma); ...
        sprintf('$\\pm2\\sigma$ (%.2f, %.2f)', media - 2*sigma, media + 2*sigma); ...
        sprintf('$\\pm3\\sigma$ (%.2f, %.2f)', media - 3*sigma, media + 3*sigma) ...
        };
    xPos2 = xLimits(1) + 0.01*(xLimits(2) - xLimits(1));
    yPos2 = yLimits(2) - 0.02*(yLimits(2) - yLimits(1));
    text(xPos2, yPos2, texto2, ...
         'Interpreter', 'latex', ...
         'HorizontalAlignment', 'left', ...
         'VerticalAlignment', 'top', ...
         'FontSize', 10, ...
         'BackgroundColor', 'w');

    hold off
end